#ifndef __COVERAGE_H__
#define __COVERAGE_H__

#if (__GNUC__ >= 10)
#define GCOV_COUNTERS 8U
#elif (__GNUC__ >= 8)
#define GCOV_COUNTERS 9U
#else
#define GCOV_COUNTERS 10U
#endif

/* The GCOV 12 gcno/gcda format has slight change,
 * Please refer to gcov-io.h in the GCC 12 for
 * more details.
 *
 * Following GCC commits introduced these changes:
 * gcc-mirror/gcc@23eb66d
 * gcc-mirror/gcc@72e0c74
 */
#if (__GNUC__ >= 12)
#define GCOV_12_FORMAT
#endif

typedef unsigned long gcov_type;

#ifdef GCOV_12_FORMAT
#define GCOV_TAG_FUNCTION_LENGTH 12
#else
#define GCOV_TAG_FUNCTION_LENGTH 3
#endif

#define GCOV_DATA_MAGIC (0x67636461)
#define GCOV_TAG_FUNCTION (0x01000000)
#define GCOV_TAG_COUNTER_BASE (0x01a10000)
#define GCOV_TAG_FOR_COUNTER(count)                                            \
  (GCOV_TAG_COUNTER_BASE + ((u32)(count) << 17))

#define FILE_START_INDICATOR '*'
#define GCOV_DUMP_SEPARATOR '<'

/**Information about counters for a single function
 *
 * This data is generated by gcc during compilation and doesn't change
 *  at run-time with the exception of the values array.
 */
struct gcov_ctr_info {
	unsigned int num;    /* number of counter values for this type */
	gcov_type *values;   /* array of counter values for this type */
};

/**
 * Profiling meta data per function
 *
 * This data is generated by gcc during compilation and doesn't change
 * at run-time.
 *
 * Information about a single function.  This uses the trailing array
 * idiom. The number of counters is determined from the merge pointer
 * array in gcov_info.  The key is used to detect which of a set of
 * comdat functions was selected -- it points to the gcov_info object
 * of the object file containing the selected comdat function.
 */
struct gcov_fn_info {
	const struct gcov_info *key;     /* comdat key */
	unsigned int ident;              /* unique ident of function */
	unsigned int lineno_checksum;    /* function lineno_checksum */
	unsigned int cfg_checksum;       /* function cfg checksum */
	struct gcov_ctr_info ctrs[1];    /* instrumented counters */
};

/** Profiling data per object file
 *
 * This data is generated by gcc during compilation and doesn't change
 * at run-time with the exception of the next pointer.
 */
struct gcov_info {
	unsigned int version;        /* Gcov version (same as GCC version) */
	struct gcov_info *next;      /* List head for a singly-linked list */
	unsigned int stamp;          /* Uniquifying time stamp */
#ifdef GCOV_12_FORMAT
	unsigned int checksum;		/* unique object checksum */
#endif
	const char *filename;        /* Name of the associated gcda data file */
	/* merge functions, null for unused*/
	void (*merge[GCOV_COUNTERS])(gcov_type *, unsigned int);
	unsigned int n_functions;         /* number of instrumented functions */
	struct gcov_fn_info **functions;  /* function information */

};

/*
 * These functions are in the header for easy access for external interface
 * reporting since they aren't useful without the structs in this header.
 */
struct gcov_info *gcov_get_list_head(void);
unsigned long gcov_populate_buffer(unsigned char *buffer, struct gcov_info *info);
unsigned long gcov_calculate_buff_size(struct gcov_info *info);

#endif
